<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * RPKI Validation
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RpkiRoa extends EntityRepository
{
    
}
