<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class RpkiValidation extends \Entities\RpkiValidation implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setTimestamp($timestamp)
    {
        $this->__load();
        return parent::setTimestamp($timestamp);
    }

    public function getTimestamp()
    {
        $this->__load();
        return parent::getTimestamp();
    }

    public function setVal($validity)
    {
        $this->__load();
        return parent::setVal($validity);
    }

    public function getVal()
    {
        $this->__load();
        return parent::getVal();
    }

    public function setInfo($info)
    {
        $this->__load();
        return parent::setInfo($info);
    }

    public function getInfo()
    {
        $this->__load();
        return parent::getInfo();
    }

    public function getRSPrefixId()
    {
        $this->__load();
        return parent::getRSPrefixId();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setRpkiRoa(\Entities\RpkiRoa $rpki_roa = NULL)
    {
        $this->__load();
        return parent::setRpkiRoa($rpki_roa);
    }

    public function getRpkiRoa()
    {
        $this->__load();
        return parent::getRpkiRoa();
    }

    public function setRSPrefix(\Entities\RSPrefix $rs_prefix = NULL)
    {
        $this->__load();
        return parent::setRSPrefix($rs_prefix);
    }

    public function getRSPrefix()
    {
        $this->__load();
        return parent::getRSPrefix();
    }

    public function setCustomer(\Entities\Customer $customer = NULL)
    {
        $this->__load();
        return parent::setCustomer($customer);
    }

    public function getCustomer()
    {
        $this->__load();
        return parent::getCustomer();
    }

    public function setValidity($validity)
    {
        $this->__load();
        return parent::setValidity($validity);
    }

    public function getValidity()
    {
        $this->__load();
        return parent::getValidity();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'validity', 'info', 'id', 'RSPrefix', 'RpkiRoa');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}